CREATE TABLE [dbo].[TBL_RELATIONMASTER] (
    [ASSID]        INT           NOT NULL,
    [REFERENCE_ID] INT           NOT NULL,
    [SPRIL_ID]     INT           NULL,
    [SIDE]         NVARCHAR (10) NOT NULL,
    CONSTRAINT [PK_TBL_RELATIONMASTER] PRIMARY KEY CLUSTERED ([ASSID] ASC)
);

